# Generated by Django 3.0.2 on 2020-01-15 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_officer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='current_latitude',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='current_longitude',
        ),
        migrations.AlterField(
            model_name='absence',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='officer',
            name='total_attendance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
